---
name: Acme-SysPath
version: 0.04
author: []
abstract: example distribution for Sys::Path
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  IO::Any: 0
  Module::Build::SysPath: 0.06
requires:
  File::Spec: 0
  IO::Any: 0
build_requires:
  Module::Build::SysPath: 0.06
provides:
  Acme::SysPath:
    file: lib/Acme/SysPath.pm
    version: 0.04
  Acme::SysPath::SPc:
    file: lib/Acme/SysPath/SPc.pm
    version: 0.04
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
